### ISSUE TITLE
Broken import on typing

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly#18]
Beware, in https://github.com/friendly-traceback/friendly/blob/399614685a92542d4570885a2acb6fe598cd48a9/friendly/rich_formatters.py#L26 the import should use `typing_info` instead of `typing`.

**Comment by aroberge** [comment]
Sorry, that was a stupid error of my part. Thanks for catching this.

New version on pypi.  (0.4.30)

**Comment by aroberge** [comment]
Added comment: I changed this in friendly_traceback yesterday, but forgot to check its effect on friendly as I thought I was not using any type annotations in friendly.
