### ISSUE TITLE
Create an interactive  display for tracebacks in Jupyter

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly#5]
In Jupyter notebooks and lab, it might be useful to have a custom ~~iPywidget~~ interactive way to have all the information available in a collapsed form. This would allow to no longer recommend the "controversial" `* import`.

**Comment by psychemedia** [comment]
This presumable complements https://github.com/friendly-traceback/friendly/issues/3 which is suggests a simple collapsible heading that states the error message as the heading with the traceback folded beneath it with a more elaborate `ipywidget`. The `ipywidget` framework supports two way callbacks between Python and Javascript environments and as such can be used to implement simple applications. What might such  widget do / look like?

Perhaps related or useful to help guide thinking about what sorts of interaction or UI are possible are tools such as as nbtutor as well as notebook variable inspectors and debuggers?

**Comment by aroberge** [comment]
What I have in mind is inspired by Thonny's assistant
![image](https://user-images.githubusercontent.com/629698/126701836-b86a52f5-5417-4fdd-895a-3284fffe620f.png)

However, the expandable elements would correspond to friendly's `what()`, `where()`, `why()`, as well as the traceback, all headed by the error message.  There would be no need of two-way communications: everything would be computed at once and presented in a collapsed state, ready for expansion.

**Comment by aroberge** [comment]
I have implemented something which is not an iPywidget but works essentially as I was hoping it would. Unfortunately, it does not currently work with the dark theme and I cannot figure out why. More explanations can be found on a [blog post](https://aroberge.blogspot.com/2021/07/new-interactive-friendly-tracebacks-for.html) I just published.

**Comment by aroberge** [comment]
After reading (again) the documentation about ipywidgets, especially [about installing them](https://ipywidgets.readthedocs.io/en/latest/user_install.html), I note the following:

> Most of the time, installing `ipywidgets` automatically configures Jupyter ...

Users of friendly are generally not expected to be experienced. Installing friendly should "just work", not simply *most* of the time, but **all** the time.

So, I will continue to work on an html-based solution, and should explore how [rich deals with jupyter](https://github.com/willmcgugan/rich/blob/master/rich/jupyter.py) in an attempt to create a more robust solution.

**Comment by aroberge** [comment]
Other than for an extra (annoying) vertical space that I cannot seem to be able to get rid of, I am happy with the result shown on https://twitter.com/andre_roberge/status/1420733729497038848

**Comment by psychemedia** [comment]
Looks useful. My preference would be to reveal the text below, rather than above, the button. With text revealed above, the button moves, with text revealed below the button stays in the same place, (so in the latter case there is less distracting motion).

**Comment by aroberge** [comment]
Ok, I am quite sure I can do this.

**Comment by aroberge** [comment]
Closing this issue as I consider the implementation to be satisfactory.
