### ISSUE TITLE
Points used as number separators

### ISSUE THREAD

**Issue by JulienPalard** [friendly-traceback/friendly#54]
Long time no see, hope you're doing well Andre!

Here's an interesting example from hkis:

```
        Traceback (most recent call last):
          File "HOME:/solution.py", line 1
            print(21.900 * 43.800 * 1.051.200)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

I think the pattern to spot is `1.051.200`, I mean where the dot is used multiple times, intended as a separator. A good occasion to remind that underscore can be used instead :)

**Comment by aroberge** [comment]
Closing as it has been now recorded for friendly-traceback (instead of friendly) as it is where the fix will be needed.
